FROM python:3.8.16

RUN mkdir /code

WORKDIR /code
COPY . .


RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip uninstall bson -y
RUN pip uninstall pymongo -y
RUN pip install pymongo 

CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=8000"]